"""
Jc Linear Fitting Viewer Module

This module provides visualization of Jc linear fitting megaplots
generated by the analysis_func.py script for the DC Test Structure Analysis Dashboard.
"""

import streamlit as st
import pandas as pd
import numpy as np
import os
import glob
from PIL import Image
from .base import AnalysisModule


class JcLinearFittingModule(AnalysisModule):
    """Jc Linear Fitting Megaplot Viewer module"""
    
    def render(self, df, **kwargs):
        st.header("📊 Jc Linear Fitting Analysis - Megaplot Viewer")
        
        st.markdown("""
        This module displays the comprehensive linear fitting megaplots generated during Jc analysis.
        Each megaplot shows all dies for a specific analysis option with:
        - Linear fit results and R² values
        - Jc values (corrected and as-drawn)
        - X-offset measurements
        - Yield boundaries (predefined, as-drawn, and fitting-based)
        """)
        
        # Extract selected_wafers from kwargs
        selected_wafers = kwargs.get('selected_wafers', None)
        
        # Get available wafers from the data
        if selected_wafers:
            available_wafers = sorted(selected_wafers)
        else:
            available_wafers = sorted(df['Wafer'].unique()) if 'Wafer' in df.columns else []
        
        if not available_wafers:
            st.warning("⚠️ No wafers available.")
            return
        
        # Sidebar controls
        col1, col2 = st.columns([1, 3])
        
        with col1:
            st.subheader("🔧 Settings")
            
            # Wafer selection
            selected_wafer = st.selectbox(
                "Select Wafer:",
                available_wafers,
                key="jc_fitting_wafer"
            )
            
            if not selected_wafer:
                st.warning("Please select a wafer.")
                return
            
            # Build path to megaplot directory
            current_dir = os.getcwd()
            parent_dir = os.path.dirname(current_dir)
            base_analysis_dir = os.path.join(parent_dir, "Wafer analysis data")
            
            # Try to find wafer directory (handle different naming conventions)
            wafer_dir = None
            if os.path.exists(base_analysis_dir):
                # st.write(f"Searching in base analysis directory: {base_analysis_dir}")
                for potential_dir in os.listdir(base_analysis_dir):
                    if selected_wafer in potential_dir:
                        wafer_dir = os.path.join(base_analysis_dir, potential_dir, "Linear fitting by die", "Megaplots")
                        # st.write(f"Found wafer directory: {wafer_dir}")
                        break

            
            if not wafer_dir or not os.path.exists(wafer_dir):
                st.warning(f"⚠️ No megaplot directory found for wafer {selected_wafer}")
                st.info(f"Expected path: `Wafer analysis data/{selected_wafer}/Linear fitting by die/Megaplots/`")
                st.info("Megaplots are generated when you run the Jc analysis with `Jc_fit_linear_regression_by_die()` function.")
                return
            
            # Find all megaplot PNG files
            megaplot_files = glob.glob(os.path.join(wafer_dir, "*_ALL_DIES_megaplot.png"))
            
            if not megaplot_files:
                st.warning(f"⚠️ No megaplot files found in {wafer_dir}")
                st.info("Run the Jc analysis to generate megaplots.")
                return
            
            # Extract option names from filenames
            option_names = []
            file_mapping = {}
            for filepath in megaplot_files:
                filename = os.path.basename(filepath)
                option_name = filename.replace("_ALL_DIES_megaplot.png", "")
                option_names.append(option_name)
                file_mapping[option_name] = filepath
            
            option_names = sorted(option_names)
            
            # Analysis option selection
            st.markdown("---")
            selected_option = st.selectbox(
                "Select Analysis Option:",
                option_names,
                key="jc_fitting_option"
            )
            
            if not selected_option:
                st.warning("Please select an analysis option.")
                return
            
            # Display file info
            st.markdown("---")
            st.markdown("**File Info:**")
            megaplot_path = file_mapping[selected_option]
            file_size = os.path.getsize(megaplot_path) / 1024  # KB
            file_mod_time = os.path.getmtime(megaplot_path)
            from datetime import datetime
            mod_time_str = datetime.fromtimestamp(file_mod_time).strftime('%Y-%m-%d %H:%M:%S')
            
            st.text(f"📁 Size: {file_size:.1f} KB")
            st.text(f"🕒 Modified: {mod_time_str}")
            
            # Download button for the image
            with open(megaplot_path, 'rb') as f:
                st.download_button(
                    label="⬇️ Download PNG",
                    data=f,
                    file_name=os.path.basename(megaplot_path),
                    mime="image/png",
                    key="download_png"
                )
            
            # Check if PDF exists
            pdf_path = megaplot_path.replace('.png', '.pdf')
            if os.path.exists(pdf_path):
                with open(pdf_path, 'rb') as f:
                    st.download_button(
                        label="⬇️ Download PDF",
                        data=f,
                        file_name=os.path.basename(pdf_path),
                        mime="application/pdf",
                        key="download_pdf"
                    )
        
        with col2:
            st.subheader(f"🖼️ Megaplot: {selected_option}")
            
            # Display the megaplot image
            try:
                image = Image.open(megaplot_path)
                
                # Display metadata
                with st.expander("ℹ️ Analysis Details", expanded=True):
                    st.markdown(f"""
                    - **Wafer:** {selected_wafer}
                    - **Analysis Option:** {selected_option}
                    - **Image Resolution:** {image.size[0]} × {image.size[1]} pixels
                    """)
                    
                    # Parse option type for additional info
                    if "Dolan_JJ" in selected_option:
                        jj_type = "Dolan Bridge Junction"
                        if "Const_W" in selected_option:
                            st.markdown("- **Variation:** Constant Width, Varying Length")
                        elif "Const_L" in selected_option:
                            st.markdown("- **Variation:** Constant Length, Varying Width")
                    elif "Manhattan_JJ" in selected_option:
                        jj_type = "Manhattan Junction"
                        if "Const_V" in selected_option:
                            st.markdown("- **Variation:** Constant Vertical Width, Varying Horizontal Width")
                        elif "Const_H" in selected_option:
                            st.markdown("- **Variation:** Constant Horizontal Width, Varying Vertical Width")
                    else:
                        jj_type = "Unknown"
                    
                    st.markdown(f"- **Junction Type:** {jj_type}")
                
                st.markdown("---")
                
                # Display the image with zoom capability
                st.image(image, use_container_width=True, caption=f"{selected_option} - All Dies Linear Fitting Results")
                
                # Additional information
                st.markdown("---")
                st.markdown("""
                ### 📖 Understanding the Megaplot
                
                Each subplot represents one die and shows:
                
                1. **Data Points:**
                   - 🔵 **Blue:** Selected data points used for linear fitting
                   - ⚪ **Gray:** Unselected/excluded data points
                
                2. **Fitting Lines:**
                   - 🔴 **Red solid:** Linear fit line with equation `y = mx + b`
                   - 🔴 **Red dotted:** ±20% boundaries from linear fit (fitting yield)
                
                3. **Ideal Resistance Lines:**
                   - 🟢 **Green solid:** Ideal 1/R calculated from predefined process bias
                   - 🟢 **Green dashed:** ±20% boundaries (predefined bias yield)
                   - 🟠 **Orange dash-dot:** As-drawn ideal 1/R (no bias correction)
                   - 🟠 **Orange dotted:** ±20% boundaries (as-drawn yield)
                
                4. **Information Box (top-left of each subplot):**
                   - Die identifier
                   - Jc (corrected with predefined bias)
                   - As-drawn Jc
                   - X offset ± error
                   - Yield percentages (predefined, as-drawn, fitting)
                
                5. **Legend:**
                   - Complete description of all curves and data series
                   - R² value indicating goodness of fit
                   - Linear regression formula
                """)
                
                # Statistics summary if data available
                if 'Option' in df.columns:
                    option_data = df[df['Option'] == selected_option]
                    if not option_data.empty and 'Jc_by_die' in option_data.columns:
                        st.markdown("### 📈 Quick Statistics")
                        
                        jc_data = option_data[option_data['Jc_by_die'].notna()]['Jc_by_die']
                        if len(jc_data) > 0:
                            col_a, col_b, col_c, col_d = st.columns(4)
                            with col_a:
                                st.metric("Mean Jc", f"{jc_data.mean():.2e} μA/μm²")
                            with col_b:
                                st.metric("Std Dev", f"{jc_data.std():.2e} μA/μm²")
                            with col_c:
                                st.metric("Min", f"{jc_data.min():.2e} μA/μm²")
                            with col_d:
                                st.metric("Max", f"{jc_data.max():.2e} μA/μm²")
                        
                        if 'Yield_by_die' in option_data.columns:
                            yield_data = option_data[option_data['Yield_by_die'].notna()]['Yield_by_die']
                            if len(yield_data) > 0:
                                st.markdown(f"**Average Yield:** {yield_data.mean()*100:.1f}%")
                
            except Exception as e:
                st.error(f"❌ Error loading image: {e}")
                st.info(f"File path: {megaplot_path}")
